version: '3.8'
services:
  db:
    image: mongo:latest
    restart: unless-stopped
  app:
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      MONGODB_URL: "mongodb://db"
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      - "../../node_modules:/app/node_modules"
      - "../../src:/app/src"
      - "../../package.json:/app/package.json"
      - "/home/elrohil/Magisterka/terraform/:/app/terraform/"
      - "../emulation-configs/:/app/emulation-configs/"
      - "../python-code-repository/:/app/python-code-repository/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

